/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.4.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.api;

import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2024-03-27T14:56:01.389439+05:30[Asia/Kolkata]", comments = "Generator version: 7.4.0")
@Validated
@Tag(name = "credit-card-application", description = "the credit-card-application API")
public interface CreditCardApplicationApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * POST /credit-card-application/submit-branch : Submitting branch credit card application
     *
     * @param body  (optional)
     * @return Application submitted successfully, customer informed (status code 201)
     */
    @Operation(
        operationId = "creditCardApplicationSubmitBranchPost",
        summary = "Submitting branch credit card application",
        responses = {
            @ApiResponse(responseCode = "201", description = "Application submitted successfully, customer informed")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/credit-card-application/submit-branch",
        consumes = { "application/json" }
    )
    
    default ResponseEntity<Void> creditCardApplicationSubmitBranchPost(
        @Parameter(name = "body", description = "") @Valid @RequestBody(required = false) Object body
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /credit-card-application/submit-online : Submitting online credit card application
     *
     * @param body  (optional)
     * @return Application submitted successfully, confirmation notification sent (status code 201)
     */
    @Operation(
        operationId = "creditCardApplicationSubmitOnlinePost",
        summary = "Submitting online credit card application",
        responses = {
            @ApiResponse(responseCode = "201", description = "Application submitted successfully, confirmation notification sent")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/credit-card-application/submit-online",
        consumes = { "application/json" }
    )
    
    default ResponseEntity<Void> creditCardApplicationSubmitOnlinePost(
        @Parameter(name = "body", description = "") @Valid @RequestBody(required = false) Object body
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
